title: Tommy Yong
subtitle: ~ Documenting My Life Musings ~
description: >- # this means to ignore newlines until "baseurl:"
author: Yong Chao Tommy, Yong
email: yongyct@gmail.com
avatar: assets/images/bitmoji.jpg

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tommyyong.ml" # the base hostname & protocol for your site

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
linkedin_url: "https://linkedin.com/in/yongyct/"
github_url: "https://github.com/yongyct"
stackoverflow_url: "https://stackoverflow.com/users/6540762/chaooder"
kaggle_url: "https://www.kaggle.com/yongyct"
medium_url: "https://medium.com/@tommyyong"
500px_url: "https://500px.com/yongyct"

# Google Analytics Tracking ID goes here:
google_analytics: UA-145379258-1

# The following settings are NECESSARY for the Prologue theme to run:
remote_theme: jekyll-theme-prologue
collections: [sections, photography]
